"""Expense Tracker category update

Revision ID: 6c1583a33a32
Revises: c07111c679a0
Create Date: 2026-02-17 00:06:19.429930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1583a33a32'
down_revision: Union[str, Sequence[str], None] = 'c07111c679a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_tracker', sa.Column('category', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_expense_tracker_category'), 'expense_tracker', ['category'], unique=False)
    op.create_index(op.f('ix_expense_tracker_exp_date'), 'expense_tracker', ['exp_date'], unique=False)
    op.create_index(op.f('ix_expense_tracker_mode'), 'expense_tracker', ['mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_tracker_mode'), table_name='expense_tracker')
    op.drop_index(op.f('ix_expense_tracker_exp_date'), table_name='expense_tracker')
    op.drop_index(op.f('ix_expense_tracker_category'), table_name='expense_tracker')
    op.drop_column('expense_tracker', 'category')
    # ### end Alembic commands ###
